# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    paths: ['DESCRIPTION']

name: Write-codemeta

jobs:
  render-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::codemeta

      - name: Write codemeta file
        run: Rscript -e 'codemeta::write_codemeta()'

      - name: Commit codemeta file
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add codemeta.json
          git commit -m "Re-write codemeta.json" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
